<a href="https://colab.research.google.com/github/nakul8820/Python-/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import pandas as pd
data = pd.read_csv("/content/nyc-east-river-bicycle-counts.csv")

from sklearn.model_selection import train_test_split

# Define features (x) and target (y)
# Assuming 'Total' is the target variable and other relevant columns are features
# You might need to adjust the features based on your specific analysis
x = data[['High Temp (°F)', 'Low Temp (°F)', 'Brooklyn Bridge', 'Manhattan Bridge', 'Williamsburg Bridge', 'Queensboro Bridge']]
y = data['Total']

x_train,x_validate,y_train,y_validate = train_test_split(x,y,test_size = 0.2,random_state = 12345)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create a Logistic Regression model
model = LogisticRegression()

# Train the model using the training data
model.fit(x_train, y_train)

# Predict on the validation set
y_pred = model.predict(x_validate)

# Evaluate the model
print("Accuracy:", accuracy_score(y_validate, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_validate, y_pred))
print("Classification Report:\n", classification_report(y_validate, y_pred))

Accuracy: 0.9285714285714286
Confusion Matrix:
 [[2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Create a Linear Regression model
linear_model = LinearRegression()

# Train the model
linear_model.fit(x_train, y_train)

# Predict on the validation set
y_pred_linear = linear_model.predict(x_validate)

# Evaluate the model
print("Mean Squared Error:", mean_squared_error(y_validate, y_pred_linear))
print("R-squared:", r2_score(y_validate, y_pred_linear))

Mean Squared Error: 1.9950808583719454e-23
R-squared: 1.0
